USE [master]
GO
/****** Object:  Database [Nba]    Script Date: 6.07.2025 22:12:09 ******/
CREATE DATABASE [Nba]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Nba', SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Nba_log', SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Nba] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Nba].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Nba] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Nba] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Nba] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Nba] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Nba] SET ARITHABORT OFF 
GO
ALTER DATABASE [Nba] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Nba] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Nba] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Nba] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Nba] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Nba] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Nba] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Nba] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Nba] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Nba] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Nba] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Nba] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Nba] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Nba] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Nba] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Nba] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Nba] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Nba] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Nba] SET  MULTI_USER 
GO
ALTER DATABASE [Nba] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Nba] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Nba] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Nba] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Nba] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Nba] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Nba] SET QUERY_STORE = ON
GO
ALTER DATABASE [Nba] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Nba]
GO
/****** Object:  Table [dbo].[Oyuncular]    Script Date: 6.07.2025 22:12:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Oyuncular](
	[OyuncuID] [int] NOT NULL,
	[TakimID] [int] NOT NULL,
	  NOT NULL,
	  NOT NULL,
	[OrtalamaSayi] [int] NOT NULL,
	[Maas] [int] NOT NULL,
 CONSTRAINT [PK_Oyuncular] PRIMARY KEY CLUSTERED 
(
	[OyuncuID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[NbaViewLamelo]    Script Date: 6.07.2025 22:12:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create view [dbo].[NbaViewLamelo]
as select * from Oyuncular Where OyuncuAd = 'Lamelo'
GO
/****** Object:  Table [dbo].[koclar]    Script Date: 6.07.2025 22:12:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[koclar](
	[KocID] [int] NOT NULL,
	[TakimID] [int] NOT NULL,
	  NOT NULL,
	  NOT NULL,
	[Maas] [int] NOT NULL,
 CONSTRAINT [PK_koclar] PRIMARY KEY CLUSTERED 
(
	[KocID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[maclar]    Script Date: 6.07.2025 22:12:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[maclar](
	[mac_id] [int] IDENTITY(1,1) NOT NULL,
	[ev_sahibi_takim_id] [int] NULL,
	[deplasman_takim_id] [int] NULL,
	[tarih] [date] NULL,
	[ev_sahibi_skor] [int] NULL,
	[deplasman_skor] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[mac_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Takimlar]    Script Date: 6.07.2025 22:12:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Takimlar](
	[TakimID] [int] NOT NULL,
	  NOT NULL,
	  NOT NULL,
	  NULL,
 CONSTRAINT [PK_Takimlar] PRIMARY KEY CLUSTERED 
(
	[TakimID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[koclar]  WITH CHECK ADD  CONSTRAINT [FK_koclar_Takimlar] FOREIGN KEY([TakimID])
REFERENCES [dbo].[Takimlar] ([TakimID])
GO
ALTER TABLE [dbo].[koclar] CHECK CONSTRAINT [FK_koclar_Takimlar]
GO
ALTER TABLE [dbo].[maclar]  WITH CHECK ADD FOREIGN KEY([deplasman_takim_id])
REFERENCES [dbo].[Takimlar] ([TakimID])
GO
ALTER TABLE [dbo].[maclar]  WITH CHECK ADD FOREIGN KEY([ev_sahibi_takim_id])
REFERENCES [dbo].[Takimlar] ([TakimID])
GO
ALTER TABLE [dbo].[Oyuncular]  WITH CHECK ADD  CONSTRAINT [FK_Oyuncular_Takimlar] FOREIGN KEY([TakimID])
REFERENCES [dbo].[Takimlar] ([TakimID])
GO
ALTER TABLE [dbo].[Oyuncular] CHECK CONSTRAINT [FK_Oyuncular_Takimlar]
GO
USE [master]
GO
ALTER DATABASE [Nba] SET  READ_WRITE 
GO
